module.exports = {
  mode: 'jit',
  purge: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: false,
  theme: {
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
    },
    fontFamily: {
      sans: ['Helvetica Neue', 'sans-serif'],
      serif: ['Georgian', 'serif'],
    },
    extend: {
      colors: {
        primary: '#b1426a',
        secondary: '#40a29b',
        tertiary: '#80c5bb',
        quaternary: '#b1426a',
        quinary: '#b1426a',
        senary: '#b1426a',
        septenary: '#9cb58f',
        octonary: '#ffd925',
        border: '#b1426a',
        background: '#ffffff',
        'gray-dark': '#212121',
        gray: '#757575',
        'gray-light': '#bdbdbd',
      },
    },
  },
  variants: {},
  plugins: [],
};
